version: "3"

services:
  # Scrapy Spider Service
  scrapy:
    build: 
      context: ./estates
    command: scrapy crawl estates
    volumes:
      - ./estates:/app
    environment:
      - DATABASE_URI=postgresql://postgres:1234@db:5432/postgres
    depends_on:
      - db
    networks:
      - sreality-net

  # Flask (HTTP Server) Service
  web:
    build:
      context: ./HTTP_server
    ports:
      - "8080:8080"
    volumes:
      - ./HTTP_server:/app
    depends_on:
      - scrapy
      - db
    networks:
      - sreality-net
    environment:
      - DATABASE_URI=postgresql://postgres:1234@db:5432/postgres


  # PostgreSQL Database Service
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - sreality-net

networks:
  sreality-net:

